global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # API Server
  - job_name: 'ai-q-api'
    static_configs:
      - targets: ['ai-q-unified-app:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['ai-q-postgres:5432']
    scrape_interval: 30s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['ai-q-redis:6379']
    scrape_interval: 30s

  # Elasticsearch
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['ai-q-elasticsearch:9200']
    metrics_path: '/_prometheus/metrics'
    scrape_interval: 30s

  # Neo4j
  - job_name: 'neo4j'
    static_configs:
      - targets: ['ai-q-neo4j:7474']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Weaviate
  - job_name: 'weaviate'
    static_configs:
      - targets: ['ai-q-weaviate:8080']
    metrics_path: '/v1/metrics'
    scrape_interval: 30s

  # MinIO
  - job_name: 'minio'
    static_configs:
      - targets: ['ai-q-minio:9000']
    metrics_path: '/minio/v2/metrics/cluster'
    scrape_interval: 30s

  # Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['ai-q-grafana:3000']

  # Web Dashboard
  - job_name: 'web-dashboard'
    static_configs:
      - targets: ['ai-q-unified-app:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 10s

  # cAdvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s

  # Docker containers
  - job_name: 'docker'
    static_configs:
      - targets: ['localhost:9323']
    scrape_interval: 15s 